/**
 * Verified Nutritional Database
 * All entries normalized to a strict 100g basis, with explicit weight types
 * (raw | cooked | edible) and standard unit weights for count-based items.
 */

export const FOOD_DATABASE = {
  // ==========================================
  // GRAINS, BREADS & BREAKFAST STAPLES
  // ==========================================
  'cooked white rice': {
    canonicalName: 'Cooked White Rice',
    aliases: ['white rice', 'cooked rice', 'choru', 'rice', 'boiled white rice', 'steamed rice'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28.0,
    fatPer100g: 0.4,
    fiberPer100g: 0.4,
    defaultServingDesc: '150g cooked portion',
    edibleWeightPerUnit: null,
    category: 'grains',
    healthTip: 'Measure weighed cooked portion on plate. 150-200g is ideal for fat-loss lunch.'
  },
  'cooked matta rice': {
    canonicalName: 'Cooked Kerala Matta Rice',
    aliases: ['matta rice', 'kerala rice', 'palakkadan matta', 'red rice', 'matta choru'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 130,
    proteinPer100g: 2.8,
    carbsPer100g: 27.5,
    fatPer100g: 0.5,
    fiberPer100g: 1.2,
    defaultServingDesc: '150g cooked portion',
    edibleWeightPerUnit: null,
    category: 'grains',
    healthTip: 'Higher fiber and micronutrients than polished white rice.'
  },
  'cooked brown rice': {
    canonicalName: 'Cooked Brown Rice',
    aliases: ['brown rice', 'cooked brown rice'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 122,
    proteinPer100g: 2.6,
    carbsPer100g: 25.0,
    fatPer100g: 0.9,
    fiberPer100g: 1.8,
    defaultServingDesc: '150g cooked portion',
    edibleWeightPerUnit: null,
    category: 'grains',
    healthTip: 'Slower digestion curve and sustained fullness.'
  },
  'oats': {
    canonicalName: 'Rolled Oats (Dry)',
    aliases: ['rolled oats', 'oatmeal', 'raw oats', 'dry oats', 'quaker oats', 'oat flakes'],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 389,
    proteinPer100g: 16.9,
    carbsPer100g: 66.3,
    fatPer100g: 6.9,
    fiberPer100g: 10.6,
    defaultServingDesc: '40g-60g dry scoop',
    edibleWeightPerUnit: null,
    category: 'grains',
    healthTip: 'Rich in beta-glucan soluble fiber for fullness and heart health.'
  },
  'idli': {
    canonicalName: 'Steamed Idli',
    aliases: ['idli', 'idlis', 'idly', 'idlys', 'steamed idli'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 125,
    proteinPer100g: 4.5,
    carbsPer100g: 26.0,
    fatPer100g: 0.5,
    fiberPer100g: 1.0,
    defaultServingDesc: '1 small piece (40g)',
    edibleWeightPerUnit: 40,
    category: 'breakfast',
    healthTip: 'Fermented, steamed, virtually fat-free. 4 small idlis (~160g) ≈ 200 kcal.'
  },
  'dosa': {
    canonicalName: 'Plain Dosa',
    aliases: ['dosa', 'dosha', 'plain dosa', 'dosai'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 150,
    proteinPer100g: 3.5,
    carbsPer100g: 27.5,
    fatPer100g: 3.1,
    fiberPer100g: 1.1,
    defaultServingDesc: '1 medium piece (80g)',
    edibleWeightPerUnit: 80,
    category: 'breakfast',
    healthTip: 'Keep oil minimal when spreading. Pair with eggs or dal for higher protein.'
  },
  'masala dosa': {
    canonicalName: 'Masala Dosa',
    aliases: ['masala dosa', 'masaladosa', 'masala dosha'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 160,
    proteinPer100g: 3.0,
    carbsPer100g: 25.3,
    fatPer100g: 5.3,
    fiberPer100g: 1.6,
    defaultServingDesc: '1 standard piece (150g)',
    edibleWeightPerUnit: 150,
    category: 'breakfast',
    healthTip: 'Potato masala filling adds carbs and tempered fat. Count as 1 main meal.'
  },
  'puttu': {
    canonicalName: 'Puttu (Rice / Ragi / Wheat)',
    aliases: ['puttu', 'ariputtu', 'wheat puttu', 'ragi puttu', 'rice puttu'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 180,
    proteinPer100g: 3.5,
    carbsPer100g: 38.0,
    fatPer100g: 1.5,
    fiberPer100g: 2.0,
    defaultServingDesc: '1 piece / cylindrical cut (100g)',
    edibleWeightPerUnit: 100,
    category: 'breakfast',
    healthTip: 'Steamed without added oil. Pair with kadala curry or 2 boiled eggs.'
  },
  'appam': {
    canonicalName: 'Appam / Palappam',
    aliases: ['appam', 'palappam', 'vellayappam', 'kallappam'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 166,
    proteinPer100g: 2.5,
    carbsPer100g: 33.3,
    fatPer100g: 2.5,
    fiberPer100g: 0.8,
    defaultServingDesc: '1 piece (60g)',
    edibleWeightPerUnit: 60,
    category: 'breakfast',
    healthTip: 'Light and easily digestible. Pair with vegetable stew or egg roast.'
  },
  'idiyappam': {
    canonicalName: 'Idiyappam (String Hoppers)',
    aliases: ['idiyappam', 'noolappam', 'string hoppers'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 150,
    proteinPer100g: 2.4,
    carbsPer100g: 32.0,
    fatPer100g: 0.8,
    fiberPer100g: 1.0,
    defaultServingDesc: '1 piece (50g)',
    edibleWeightPerUnit: 50,
    category: 'breakfast',
    healthTip: 'Steamed rice noodles. Great light carb foundation.'
  },
  'chapati': {
    canonicalName: 'Whole Wheat Chapati / Roti',
    aliases: ['chapati', 'chapatis', 'chappathi', 'chappathis', 'roti', 'rotis', 'phulka', 'phulkas'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 237,
    proteinPer100g: 8.0,
    carbsPer100g: 45.0,
    fatPer100g: 3.8,
    fiberPer100g: 6.5,
    defaultServingDesc: '1 standard medium chapati (35g)',
    edibleWeightPerUnit: 35,
    category: 'breads',
    healthTip: '1 medium chapati (35g) ≈ 83 kcal. 2 chapatis (70g) ≈ 166 kcal.'
  },
  'porotta': {
    canonicalName: 'Kerala Porotta',
    aliases: ['porotta', 'parotta', 'kerala parotta', 'malabar parotta'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 350,
    proteinPer100g: 6.2,
    carbsPer100g: 47.5,
    fatPer100g: 15.0,
    fiberPer100g: 1.5,
    defaultServingDesc: '1 medium porotta (80g)',
    edibleWeightPerUnit: 80,
    category: 'breads',
    healthTip: 'High in refined flour and oil (1 piece ≈ 280 kcal). Prefer whole wheat chapati for fat loss.'
  },

  // ==========================================
  // EGGS & POULTRY
  // ==========================================
  'boiled egg': {
    canonicalName: 'Whole Boiled Egg',
    aliases: ['boiled egg', 'boiled eggs', 'egg', 'eggs', 'mutta', 'puzhungiya mutta', 'hard boiled egg', 'soft boiled egg'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 148,
    proteinPer100g: 12.6,
    carbsPer100g: 0.8,
    fatPer100g: 10.0,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 large egg (50g edible)',
    edibleWeightPerUnit: 50,
    category: 'proteins',
    healthTip: 'Complete protein standard. 1 egg (50g) = 74 kcal, 6.3g protein. 2 eggs = 148 kcal, 12.6g protein.'
  },
  'egg white': {
    canonicalName: 'Egg White (Boiled/Cooked)',
    aliases: ['egg white', 'egg whites', 'mutta vella', 'white of egg'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 52,
    proteinPer100g: 11.0,
    carbsPer100g: 0.7,
    fatPer100g: 0.2,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 egg white (33g)',
    edibleWeightPerUnit: 33,
    category: 'proteins',
    healthTip: 'Pure lean protein. 1 white (33g) ≈ 17 kcal, 3.6g protein. Perfect for hitting protein goals without fat.'
  },
  'omelette': {
    canonicalName: '2-Egg Omelette',
    aliases: ['omelette', 'omlet', 'egg omelette', 'mutta omelette'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 154,
    proteinPer100g: 11.1,
    carbsPer100g: 1.7,
    fatPer100g: 11.5,
    fiberPer100g: 0.2,
    defaultServingDesc: '1 serving (2 eggs, 115g)',
    edibleWeightPerUnit: 115,
    category: 'proteins',
    healthTip: 'Cook on non-stick pan with spray oil to keep total calories under 180 kcal.'
  },
  'chicken breast': {
    canonicalName: 'Cooked Chicken Breast (Skinless/Boneless)',
    aliases: ['chicken breast', 'grilled chicken breast', 'boiled chicken breast', 'cooked chicken breast', 'lean chicken'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 165,
    proteinPer100g: 31.0,
    carbsPer100g: 0.0,
    fatPer100g: 3.6,
    fiberPer100g: 0.0,
    defaultServingDesc: '150g cooked portion',
    edibleWeightPerUnit: null,
    category: 'proteins',
    healthTip: 'Top-tier lean protein. 150g cooked = 247.5 kcal, 46.5g protein.'
  },
  'chicken curry': {
    canonicalName: 'Kerala Chicken Curry',
    aliases: ['chicken curry', 'kerala chicken curry', 'kozhi curry', 'nadan chicken curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 155,
    proteinPer100g: 16.5,
    carbsPer100g: 3.0,
    fatPer100g: 8.5,
    fiberPer100g: 0.5,
    defaultServingDesc: '150g chicken pieces + light gravy',
    edibleWeightPerUnit: null,
    category: 'proteins',
    healthTip: 'Focus on chicken pieces and moderate the coconut oil gravy.'
  },
  'chicken kurma': {
    canonicalName: 'Chicken Kurma',
    aliases: ['chicken kurma', 'chicken korma', 'white kurma'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 175,
    proteinPer100g: 15.0,
    carbsPer100g: 4.5,
    fatPer100g: 10.8,
    fiberPer100g: 0.8,
    defaultServingDesc: '150g portion',
    edibleWeightPerUnit: null,
    category: 'proteins',
    healthTip: 'Cashew and coconut milk base increases fat content.'
  },

  // ==========================================
  // FISH & SEAFOOD
  // ==========================================
  'mathi fry': {
    canonicalName: 'Fish Fry (Mathi / Sardine)',
    aliases: ['mathi fry', 'sardine fry', 'chaala fry', 'fried mathi', 'fried sardine', 'fish fry', 'fried fish'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 200,
    proteinPer100g: 20.4,
    carbsPer100g: 2.2,
    fatPer100g: 12.2,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 piece (45g edible)',
    edibleWeightPerUnit: 45,
    category: 'seafood',
    confidence: 'estimated_range',
    healthTip: 'Recipe estimated: ~120 kcal per 60g. Calorie density varies with fish type, batter coating, and oil absorption.'
  },
  'chicken kurma': {
    canonicalName: 'Chicken Kurma (Korma)',
    aliases: ['chicken kurma', 'chicken korma', 'korma', 'kurma', 'chicken curry with gravy', 'chicken stew'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 150,
    proteinPer100g: 12.0,
    carbsPer100g: 4.5,
    fatPer100g: 9.0,
    fiberPer100g: 0.8,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'proteins',
    confidence: 'estimated_range',
    healthTip: 'Recipe estimated: ~105 kcal for 70g. Calories vary with coconut paste, cashew, or cream.'
  },
  'cucumber': {
    canonicalName: 'Fresh Cucumber (Raw/Sliced)',
    aliases: ['cucumber', 'salad cucumber', 'vellarikka', 'kheera', 'cucumber slices', 'sliced cucumber', 'raw cucumber'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    fiberPer100g: 0.5,
    defaultServingDesc: '1 medium cucumber (150-200g)',
    edibleWeightPerUnit: 150,
    category: 'vegetables',
    confidence: 'verified',
    healthTip: '96% water content! Excellent for hydration and low-calorie fullness.'
  },
  'banana thoran no coconut': {
    canonicalName: 'Banana Thoran (No Coconut)',
    aliases: ['banana thoran no coconut', 'vazhakka thoran no coconut', 'ethakka thoran no coconut', 'banana thoran without coconut', 'ethakka thoran without coconut', 'vazhakka thoran without coconut', 'banana thoran 150 g no coconut', 'banana thoran 150g no coconut'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 55,
    proteinPer100g: 1.2,
    carbsPer100g: 12.0,
    fatPer100g: 0.8,
    fiberPer100g: 2.5,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    confidence: 'verified',
    healthTip: 'No coconut preparation saves ~40-60 kcal compared to traditional thoran!'
  },
  'banana thoran': {
    canonicalName: 'Raw Banana (Ethakka / Vazhakka) Thoran',
    aliases: ['banana thoran', 'vazhakka thoran', 'ethakka thoran', 'plantain thoran', 'green banana thoran', 'ethakka mezhukkupuratti'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 80,
    proteinPer100g: 1.5,
    carbsPer100g: 13.5,
    fatPer100g: 2.5,
    fiberPer100g: 2.8,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    confidence: 'estimated_range',
    healthTip: 'Traditional Kerala side dish with raw plantain.'
  },
  'mathi curry': {
    canonicalName: 'Mathi (Sardine) Curry (Kudampuli style)',
    aliases: ['mathi curry', 'sardine curry', 'chaala curry', 'kudampuli mathi curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 125,
    proteinPer100g: 18.5,
    carbsPer100g: 1.2,
    fatPer100g: 5.0,
    fiberPer100g: 0.0,
    defaultServingDesc: '100g fish + light gravy',
    edibleWeightPerUnit: null,
    category: 'seafood',
    healthTip: 'Omega-3 powerhouse with zero oil absorption compared to fried fish.'
  },
  'ayala fry': {
    canonicalName: 'Ayala (Mackerel) Fry',
    aliases: ['ayala fry', 'mackerel fry', 'fried ayala', 'fried mackerel'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 200,
    proteinPer100g: 23.3,
    carbsPer100g: 2.2,
    fatPer100g: 11.1,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 piece / half fish (90g)',
    edibleWeightPerUnit: 90,
    category: 'seafood',
    healthTip: 'High protein fish rich in healthy marine fats. Tawa shallow fry preferred.'
  },
  'ayala curry': {
    canonicalName: 'Ayala (Mackerel) Curry',
    aliases: ['ayala curry', 'mackerel curry', 'ayala mulakittathu'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 140,
    proteinPer100g: 20.5,
    carbsPer100g: 1.5,
    fatPer100g: 6.0,
    fiberPer100g: 0.0,
    defaultServingDesc: '100g fish + gravy',
    edibleWeightPerUnit: null,
    category: 'seafood',
    healthTip: 'Lean, clean protein curry.'
  },
  'neymeen fry': {
    canonicalName: 'Neymeen / Kingfish (Seer Fish) Fry',
    aliases: ['neymeen fry', 'seer fish fry', 'kingfish fry', 'ayakoora fry', 'vanjaram fry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 180,
    proteinPer100g: 22.5,
    carbsPer100g: 1.7,
    fatPer100g: 9.2,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 slice (120g edible)',
    edibleWeightPerUnit: 120,
    category: 'seafood',
    healthTip: 'Meaty steak fish with no small bones. High satiety protein.'
  },
  'choora fry': {
    canonicalName: 'Choora (Tuna) Fry',
    aliases: ['choora fry', 'tuna fry', 'fried tuna', 'kera fry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 175,
    proteinPer100g: 26.0,
    carbsPer100g: 2.0,
    fatPer100g: 7.0,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 piece (100g)',
    edibleWeightPerUnit: 100,
    category: 'seafood',
    healthTip: 'Ultra-dense protein source for muscle preservation.'
  },
  'choora curry': {
    canonicalName: 'Choora (Tuna) Curry',
    aliases: ['choora curry', 'tuna curry', 'kera curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 130,
    proteinPer100g: 25.0,
    carbsPer100g: 1.0,
    fatPer100g: 2.5,
    fiberPer100g: 0.0,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'seafood',
    healthTip: '25g protein with under 3g fat per 100g!'
  },
  'karimeen fry': {
    canonicalName: 'Karimeen (Pearl Spot) Fry',
    aliases: ['karimeen fry', 'pearl spot fry', 'fried karimeen'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 162,
    proteinPer100g: 20.0,
    carbsPer100g: 2.1,
    fatPer100g: 7.9,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 fish (120g edible)',
    edibleWeightPerUnit: 120,
    category: 'seafood',
    healthTip: 'Delicate, lean white fish.'
  },
  'prawns roast': {
    canonicalName: 'Prawns / Shrimp Roast',
    aliases: ['prawns roast', 'chemmeen roast', 'prawns fry', 'chemmeen fry', 'shrimp roast'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 135,
    proteinPer100g: 23.0,
    carbsPer100g: 3.5,
    fatPer100g: 3.2,
    fiberPer100g: 0.0,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'seafood',
    healthTip: 'Super high protein, very low calorie seafood.'
  },
  'fish curry': {
    canonicalName: 'Kerala Fish Curry (Kudampuli style)',
    aliases: ['fish curry', 'meen curry', 'kerala fish curry', 'kudampuli fish curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 135,
    proteinPer100g: 19.5,
    carbsPer100g: 1.5,
    fatPer100g: 5.5,
    fiberPer100g: 0.0,
    defaultServingDesc: '100g fish + gravy',
    edibleWeightPerUnit: null,
    category: 'seafood',
    healthTip: 'Low calorie and rich in protein and Omega-3s.'
  },

  // ==========================================
  // VEGETABLES, THORANS & CURRIES
  // ==========================================
  'kumbalanga curry': {
    canonicalName: 'Kumbalanga (Ash Gourd) Curry / Olan',
    aliases: ['kumbalanga curry', 'kumbalanga olan', 'ash gourd curry', 'kumbalanga', 'kumalanga curry', 'kumalanga', 'ash gourd'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 50,
    proteinPer100g: 1.5,
    carbsPer100g: 5.5,
    fatPer100g: 2.3,
    fiberPer100g: 1.8,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: '60g = 30 kcal. Extremely hydrating, cooling, high fiber vegetable curry.'
  },
  'banana thoran': {
    canonicalName: 'Vazhakka (Raw Banana / Plantain) Thoran',
    aliases: ['banana thoran', 'vazhakka thoran', 'kaya thoran', 'raw banana thoran', 'pacha kaya thoran', 'plantain thoran'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 75,
    proteinPer100g: 1.8,
    carbsPer100g: 14.0,
    fatPer100g: 1.2,
    fiberPer100g: 2.5,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: '150g without coconut ≈ 112 kcal. Rich in resistant starch for gut microbiome.'
  },
  'beetroot thoran': {
    canonicalName: 'Beetroot Thoran / Upperi',
    aliases: ['beetroot thoran', 'beetroot upperi', 'beetroot mezhukkupuratti', 'beetroot'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 85,
    proteinPer100g: 2.2,
    carbsPer100g: 12.0,
    fatPer100g: 3.5,
    fiberPer100g: 2.8,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: 'Rich in dietary nitrates to boost blood flow and walk stamina.'
  },
  'cabbage thoran': {
    canonicalName: 'Cabbage Thoran',
    aliases: ['cabbage thoran', 'cabbage upperi', 'cabbage'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 75,
    proteinPer100g: 2.0,
    carbsPer100g: 8.0,
    fatPer100g: 3.8,
    fiberPer100g: 2.5,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: 'High volume, low calorie fiber source.'
  },
  'payar thoran': {
    canonicalName: 'Payar (Green Gram / Cowpeas / Long Beans) Thoran',
    aliases: ['payar thoran', 'cherupayar thoran', 'vanpayar thoran', 'achinga payar thoran', 'payar'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 110,
    proteinPer100g: 6.5,
    carbsPer100g: 15.0,
    fatPer100g: 3.2,
    fiberPer100g: 4.5,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: 'High protein plant-based side! Great for muscle preservation.'
  },
  'pavakka thoran': {
    canonicalName: 'Pavakka (Bitter Gourd) & Payar Thoran',
    aliases: ['pavakka thoran', 'bitter gourd thoran', 'bitter melon thoran', 'pavakka payar thoran', 'pavakka'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 80,
    proteinPer100g: 3.2,
    carbsPer100g: 10.0,
    fatPer100g: 3.0,
    fiberPer100g: 3.2,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: 'Helps improve insulin sensitivity and post-meal glucose stability.'
  },
  'avial': {
    canonicalName: 'Kerala Avial',
    aliases: ['avial', 'kerala avial', 'avial curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 93,
    proteinPer100g: 2.5,
    carbsPer100g: 10.7,
    fatPer100g: 4.5,
    fiberPer100g: 3.0,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    healthTip: 'Nutrient-dense mixed vegetables with curd and coconut paste.'
  },
  'sambar': {
    canonicalName: 'Kerala Sambar',
    aliases: ['sambar', 'sambhar', 'kerala sambar', 'dal sambar'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 73,
    proteinPer100g: 3.0,
    carbsPer100g: 10.0,
    fatPer100g: 2.3,
    fiberPer100g: 2.2,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'curries',
    healthTip: 'Toor dal with vegetables and spices. 150g bowl ≈ 110 kcal.'
  },
  'dal curry': {
    canonicalName: 'Parippu (Lentil / Dal) Curry',
    aliases: ['dal', 'dal curry', 'parippu curry', 'parippu', 'daal', 'toor dal', 'cherupayar parippu'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 93,
    proteinPer100g: 5.0,
    carbsPer100g: 13.3,
    fatPer100g: 2.1,
    fiberPer100g: 3.5,
    defaultServingDesc: '1 bowl (150g)',
    edibleWeightPerUnit: null,
    category: 'curries',
    healthTip: 'Plant protein staple with complex carbohydrates.'
  },
  'green peas curry': {
    canonicalName: 'Green Peas Curry',
    aliases: ['green peas', 'green peas curry', 'peas curry', 'pattani curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 115,
    proteinPer100g: 5.8,
    carbsPer100g: 16.0,
    fatPer100g: 3.5,
    fiberPer100g: 4.2,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'curries',
    healthTip: 'Plant protein with high satiety.'
  },
  'kadala curry': {
    canonicalName: 'Kadala Curry (Black Chickpeas)',
    aliases: ['kadala curry', 'kadala', 'black chickpea curry', 'chickpea curry'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 145,
    proteinPer100g: 7.2,
    carbsPer100g: 19.0,
    fatPer100g: 4.8,
    fiberPer100g: 5.5,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: null,
    category: 'curries',
    healthTip: 'Traditional pairing with Puttu. High fiber and complex carbs.'
  },
  'boiled corn': {
    canonicalName: 'Boiled Sweet Corn',
    aliases: ['corn', 'sweet corn', 'sweetcorn', 'boiled corn', 'cholam'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 86,
    proteinPer100g: 3.0,
    carbsPer100g: 18.7,
    fatPer100g: 1.2,
    fiberPer100g: 2.4,
    defaultServingDesc: '90g boiled serving',
    edibleWeightPerUnit: 90,
    category: 'vegetables',
    healthTip: '90g boiled corn ≈ 78 kcal. Great post-walk fiber and carb replenishment.'
  },
  'cucumber': {
    canonicalName: 'Fresh Cucumber',
    aliases: ['cucumber', 'vellarikka', 'kheera', 'cucumber salad'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 15,
    proteinPer100g: 0.7,
    carbsPer100g: 3.6,
    fatPer100g: 0.1,
    fiberPer100g: 0.5,
    defaultServingDesc: '1 medium cucumber (150g)',
    edibleWeightPerUnit: 150,
    category: 'vegetables',
    healthTip: 'Zero guilt high volume food! Over 95% water.'
  },
  'coconut chutney': {
    canonicalName: 'Fresh Coconut Chutney',
    aliases: ['coconut chutney', 'chutney', 'thenga chutney', 'white chutney', 'chutni'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 180,
    proteinPer100g: 2.5,
    carbsPer100g: 6.0,
    fatPer100g: 16.0,
    fiberPer100g: 4.0,
    defaultServingDesc: '1-2 tbsp (25g)',
    edibleWeightPerUnit: 25,
    category: 'condiments',
    healthTip: '1-2 tbsp (~25g) ≈ 45 kcal. Healthy medium chain triglycerides (MCTs).'
  },

  // ==========================================
  // FRUITS
  // ==========================================
  'pomegranate': {
    canonicalName: 'Pomegranate (Edible Arils)',
    aliases: ['pomegranate', 'pomegranate arils', 'mathalam', 'anar', 'pomogranate', 'pomegranates'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 83,
    proteinPer100g: 1.7,
    carbsPer100g: 18.7,
    fatPer100g: 1.2,
    fiberPer100g: 4.0,
    defaultServingDesc: '40g edible arils',
    edibleWeightPerUnit: null,
    category: 'fruits',
    healthTip: '40g edible arils ≈ 33.2 kcal. Rich in punicalagins, polyphenols, and antioxidants.'
  },
  'banana': {
    canonicalName: 'Fresh Banana',
    aliases: ['banana', 'bananas', 'pazham', 'nendran pazham', 'robusta', 'poovan pazham'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 22.8,
    fatPer100g: 0.3,
    fiberPer100g: 2.6,
    defaultServingDesc: '1 medium fruit (110g edible)',
    edibleWeightPerUnit: 110,
    category: 'fruits',
    healthTip: '130g edible banana ≈ 115.7 kcal. Natural potassium and quick glycogen for walks.'
  },
  'apple': {
    canonicalName: 'Fresh Apple',
    aliases: ['apple', 'apples', 'green apple', 'red apple'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    fiberPer100g: 2.4,
    defaultServingDesc: '1 medium apple (150g)',
    edibleWeightPerUnit: 150,
    category: 'fruits',
    healthTip: '1 medium (150g) ≈ 78 kcal. Pectin soluble fiber keeps hunger away.'
  },
  'orange': {
    canonicalName: 'Fresh Orange',
    aliases: ['orange', 'oranges', 'mandarin', 'santra', 'mosambi'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 11.8,
    fatPer100g: 0.1,
    fiberPer100g: 2.4,
    defaultServingDesc: '1 medium fruit (130g)',
    edibleWeightPerUnit: 130,
    category: 'fruits',
    healthTip: '1 medium (130g) ≈ 61 kcal. High Vitamin C and low glycemic index.'
  },
  'grapes': {
    canonicalName: 'Fresh Grapes',
    aliases: ['grapes', 'grape', 'green grapes', 'black grapes', 'munthiri'],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 69,
    proteinPer100g: 0.7,
    carbsPer100g: 18.1,
    fatPer100g: 0.2,
    fiberPer100g: 0.9,
    defaultServingDesc: '1 small cup (100g)',
    edibleWeightPerUnit: null,
    category: 'fruits',
    healthTip: 'Rich in resveratrol.'
  },

  // ==========================================
  // RESTAURANT / SOCIAL / DINING OUT
  // ==========================================
  'shawaya': {
    canonicalName: 'Shawaya Rotisserie Grilled Chicken',
    aliases: ['shawaya', 'shawaya chicken', 'shawayah', 'rotisserie chicken arabian'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 155,
    proteinPer100g: 21.0,
    carbsPer100g: 0.3,
    fatPer100g: 7.8,
    fiberPer100g: 0.0,
    defaultServingDesc: 'Quarter chicken (180g)',
    edibleWeightPerUnit: 180,
    category: 'dining_out',
    healthTip: 'Charcoal/rotisserie roasted! 1/4 chicken ≈ 280 kcal, 38g protein. Top fat-loss dining choice.'
  },
  'alfaham': {
    canonicalName: 'Al Faham Grilled Chicken',
    aliases: ['alfaham', 'al faham', 'al-faham', 'alfaham chicken', 'bbq chicken arabian'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 145,
    proteinPer100g: 19.0,
    carbsPer100g: 1.1,
    fatPer100g: 7.2,
    fiberPer100g: 0.0,
    defaultServingDesc: 'Quarter chicken (180g)',
    edibleWeightPerUnit: 180,
    category: 'dining_out',
    healthTip: 'Charcoal grilled! High protein, low carb dining out staple.'
  },
  'chicken mandi': {
    canonicalName: 'Chicken Mandi',
    aliases: ['mandi', 'chicken mandi', 'kuzhimandi', 'kuzhi mandi'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 192,
    proteinPer100g: 12.8,
    carbsPer100g: 22.0,
    fatPer100g: 6.0,
    fiberPer100g: 0.8,
    defaultServingDesc: '1 portion (250g)',
    edibleWeightPerUnit: 250,
    category: 'dining_out',
    healthTip: 'Focus on eating the chicken; eat half the rice portion and skip mayonnaise to save 180 kcal.'
  },
  'chicken biryani': {
    canonicalName: 'Malabar / Dum Chicken Biryani',
    aliases: ['biryani', 'chicken biryani', 'biriyani', 'malabar biryani', 'dum biryani'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 187,
    proteinPer100g: 9.3,
    carbsPer100g: 22.7,
    fatPer100g: 6.7,
    fiberPer100g: 1.0,
    defaultServingDesc: '1 plate (300g)',
    edibleWeightPerUnit: 300,
    category: 'dining_out',
    healthTip: '300g plate ≈ 560 kcal. Eat slowly and balance with daily 5km walk.'
  },
  'shawarma': {
    canonicalName: 'Chicken Shawarma Roll',
    aliases: ['shawarma', 'shawarma roll', 'chicken shawarma'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 210,
    proteinPer100g: 11.0,
    carbsPer100g: 22.5,
    fatPer100g: 8.5,
    fiberPer100g: 1.2,
    defaultServingDesc: '1 roll (200g)',
    edibleWeightPerUnit: 200,
    category: 'dining_out',
    healthTip: 'Ask for no-mayo or extra lettuce/garlic to save 120 kcal.'
  },

  // ==========================================
  // BEVERAGES & SUPPLEMENTS
  // ==========================================
  'tea with milk': {
    canonicalName: 'Milk Tea with 1 tsp Sugar',
    aliases: ['tea', 'chai', 'milk tea', 'karak tea', 'chaya'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 54,
    proteinPer100g: 1.8,
    carbsPer100g: 7.1,
    fatPer100g: 2.1,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 cup (120ml)',
    edibleWeightPerUnit: 120,
    category: 'beverages',
    healthTip: 'Switch to black tea or sugar-free to save calories.'
  },
  'black coffee': {
    canonicalName: 'Black Coffee / Green Tea / Sulaimani (No Sugar)',
    aliases: ['coffee', 'black coffee', 'black tea', 'sulaimani', 'green tea', 'kattan chaya', 'kattan kapi'],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 1,
    proteinPer100g: 0.1,
    carbsPer100g: 0.1,
    fatPer100g: 0.0,
    fiberPer100g: 0.0,
    defaultServingDesc: '1 cup (150ml)',
    edibleWeightPerUnit: 150,
    category: 'beverages',
    healthTip: 'Virtually zero calorie metabolic and walk stamina booster.'
  },
  'whey protein': {
    canonicalName: 'Whey Protein Scoop in Water',
    aliases: ['whey protein', 'whey', 'protein powder', 'protein shake'],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 400,
    proteinPer100g: 80.0,
    carbsPer100g: 8.3,
    fatPer100g: 5.0,
    fiberPer100g: 0.5,
    defaultServingDesc: '1 scoop (30g)',
    edibleWeightPerUnit: 30,
    category: 'supplements',
    healthTip: '1 scoop (30g) in water = 120 kcal, 24g pure protein.'
  }
  'kappa puzhukku': {
    canonicalName: 'Kappa (Boiled Tapioca / Cassava)',
    aliases: ["kappa","boiled tapioca","kappa puzhukku","boiled cassava","maravalli kizhangu"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 160,
    proteinPer100g: 1.4,
    carbsPer100g: 38.1,
    fatPer100g: 0.3,
    fiberPer100g: 1.8,
    defaultServingDesc: '150g boiled portion',
    edibleWeightPerUnit: null,
    category: 'grains',
    confidence: 'verified',
    healthTip: 'Traditional Kerala carbohydrate staple. High energy density.'
  },
  'kerala puttu': {
    canonicalName: 'Rice Puttu (Steamed Cylindrical Rice Cake)',
    aliases: ["puttu","kerala puttu","rice puttu","ari puttu"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 156,
    proteinPer100g: 3.1,
    carbsPer100g: 33.2,
    fatPer100g: 1.2,
    fiberPer100g: 1.4,
    defaultServingDesc: '1 puttu portion (120g)',
    edibleWeightPerUnit: 120,
    category: 'grains',
    confidence: 'verified',
    healthTip: 'Steamed rice flour with light coconut layers. 1 piece ≈ 187 kcal.'
  },
  'moru curry': {
    canonicalName: 'Kerala Moru (Spiced Buttermilk) Curry / Pulissery',
    aliases: ["moru curry","moru kachiyathu","pulissery","kachiya moru","buttermilk curry"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 45,
    proteinPer100g: 2.1,
    carbsPer100g: 3.8,
    fatPer100g: 2.2,
    fiberPer100g: 0.5,
    defaultServingDesc: '1 cup (150ml)',
    edibleWeightPerUnit: null,
    category: 'curries',
    confidence: 'estimated_range',
    healthTip: 'Probiotic-rich digestive curry made with sour curd and turmeric.'
  },
  'beans thoran': {
    canonicalName: 'French Beans Thoran / Poriyal',
    aliases: ["beans thoran","french beans thoran","beans poriyal","green beans thoran"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 70,
    proteinPer100g: 2.2,
    carbsPer100g: 7.8,
    fatPer100g: 3.2,
    fiberPer100g: 3.4,
    defaultServingDesc: '1 bowl (100g)',
    edibleWeightPerUnit: null,
    category: 'vegetables',
    confidence: 'estimated_range',
    healthTip: 'Rich in dietary fiber and folate.'
  },
  'meen pollichathu': {
    canonicalName: 'Meen Pollichathu (Banana Leaf Wrapped Pearlspot / Karimeen)',
    aliases: ["meen pollichathu","karimeen pollichathu","fish pollichathu","fish in banana leaf"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 165,
    proteinPer100g: 19.5,
    carbsPer100g: 3.5,
    fatPer100g: 8,
    fiberPer100g: 1,
    defaultServingDesc: '1 fish (150g edible)',
    edibleWeightPerUnit: 150,
    category: 'seafood',
    confidence: 'estimated_range',
    healthTip: 'Traditional shallow roasted fish in shallot-tomato masala wrapped in banana leaf.'
  },
  'paneer low fat': {
    canonicalName: 'Low-Fat Cottage Cheese / Paneer (Raw/Cooked)',
    aliases: ["low fat paneer","diet paneer","light paneer","skim paneer"],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 175,
    proteinPer100g: 22,
    carbsPer100g: 4.5,
    fatPer100g: 7.5,
    fiberPer100g: 0,
    defaultServingDesc: '100g portion',
    edibleWeightPerUnit: 100,
    category: 'proteins',
    confidence: 'verified',
    healthTip: 'Slow-digesting casein protein. Great for overnight muscle repair.'
  },
  'tofu firm': {
    canonicalName: 'Firm Tofu (Soy Bean Curd)',
    aliases: ["tofu","firm tofu","organic tofu","soy tofu"],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 83,
    proteinPer100g: 10,
    carbsPer100g: 1.9,
    fatPer100g: 4.8,
    fiberPer100g: 1.2,
    defaultServingDesc: '100g slice',
    edibleWeightPerUnit: 100,
    category: 'proteins',
    confidence: 'verified',
    healthTip: 'Complete plant protein with all 9 essential amino acids and zero cholesterol.'
  },
  'whey protein isolate': {
    canonicalName: '100% Whey Protein Isolate (1 Scoop / 30g)',
    aliases: ["whey protein","whey isolate","protein powder","1 scoop whey","isolate protein","whey shake"],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 370,
    proteinPer100g: 88,
    carbsPer100g: 2,
    fatPer100g: 1,
    fiberPer100g: 0.5,
    defaultServingDesc: '1 scoop (30g powder = 111 kcal, 26.4g protein)',
    edibleWeightPerUnit: 30,
    category: 'proteins',
    confidence: 'verified',
    healthTip: 'Fastest absorbing bio-available protein. Peak leucine for muscle protein synthesis.'
  },
  'soya chunks': {
    canonicalName: 'Soya Chunks / Mealmaker (Dry/Boiled)',
    aliases: ["soya chunks","mealmaker","soy chunks","boiled soya chunks","soya"],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 345,
    proteinPer100g: 52,
    carbsPer100g: 33,
    fatPer100g: 0.5,
    fiberPer100g: 13,
    defaultServingDesc: '30g dry (yields 90g boiled) = 104 kcal, 15.6g protein',
    edibleWeightPerUnit: 30,
    category: 'proteins',
    confidence: 'verified',
    healthTip: 'Highest protein density of any plant food (52% protein by dry weight).'
  },
  'greek yogurt plain': {
    canonicalName: 'Plain Greek Yogurt (0% Non-Fat)',
    aliases: ["greek yogurt","plain greek yogurt","nonfat greek yogurt","0% greek yogurt"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 59,
    proteinPer100g: 10.3,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fiberPer100g: 0,
    defaultServingDesc: '1 cup (170g) = 100 kcal, 17.5g protein',
    edibleWeightPerUnit: 170,
    category: 'dairy',
    confidence: 'verified',
    healthTip: 'Strained yogurt with double the protein and half the carbohydrates of standard curd.'
  },
  'chia seeds': {
    canonicalName: 'Raw Chia Seeds',
    aliases: ["chia seeds","chia","soaked chia seeds","chia seed"],
    basis: '100g',
    weightType: 'raw',
    caloriesPer100g: 486,
    proteinPer100g: 16.5,
    carbsPer100g: 42.1,
    fatPer100g: 30.7,
    fiberPer100g: 34.4,
    defaultServingDesc: '1 tbsp (15g) = 73 kcal, 5.2g fiber',
    edibleWeightPerUnit: 15,
    category: 'nuts_seeds',
    confidence: 'verified',
    healthTip: 'Soluble fiber gel that expands 10x in water to promote sustained satiety.'
  },
  'almonds raw': {
    canonicalName: 'Raw Whole Almonds',
    aliases: ["almonds","raw almonds","badam","soaked almonds"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 579,
    proteinPer100g: 21.2,
    carbsPer100g: 21.6,
    fatPer100g: 49.9,
    fiberPer100g: 12.5,
    defaultServingDesc: '10 almonds (12g) = 69 kcal',
    edibleWeightPerUnit: 12,
    category: 'nuts_seeds',
    confidence: 'verified',
    healthTip: 'Rich in Vitamin E and monounsaturated healthy fats.'
  },
  'walnuts': {
    canonicalName: 'Raw Walnut Halves',
    aliases: ["walnuts","raw walnuts","akhrot","walnut kernels"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 654,
    proteinPer100g: 15.2,
    carbsPer100g: 13.7,
    fatPer100g: 65.2,
    fiberPer100g: 6.7,
    defaultServingDesc: '4 walnut halves (14g) = 92 kcal',
    edibleWeightPerUnit: 14,
    category: 'nuts_seeds',
    confidence: 'verified',
    healthTip: 'Plant-based Alpha-Linolenic Acid (ALA) Omega-3 powerhouse.'
  },
  'guava fresh': {
    canonicalName: 'Fresh Guava (Raw/Edible with Skin)',
    aliases: ["guava","fresh guava","pera","amrood","koyyaka"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 68,
    proteinPer100g: 2.6,
    carbsPer100g: 14.3,
    fatPer100g: 0.9,
    fiberPer100g: 5.4,
    defaultServingDesc: '1 medium guava (120g) = 82 kcal, 6.5g fiber',
    edibleWeightPerUnit: 120,
    category: 'fruits',
    confidence: 'verified',
    healthTip: 'Contains 4x more Vitamin C than oranges with high pectin soluble fiber.'
  },
  'papaya ripe': {
    canonicalName: 'Fresh Ripe Papaya Slices',
    aliases: ["papaya","ripe papaya","papaya slices","omakka","pappali"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 43,
    proteinPer100g: 0.5,
    carbsPer100g: 10.8,
    fatPer100g: 0.3,
    fiberPer100g: 1.7,
    defaultServingDesc: '1 cup cubed (150g) = 65 kcal',
    edibleWeightPerUnit: 150,
    category: 'fruits',
    confidence: 'verified',
    healthTip: 'Contains papain enzyme for protein digestion and gut health.'
  },
  'watermelon fresh': {
    canonicalName: 'Fresh Watermelon Chunks',
    aliases: ["watermelon","fresh watermelon","tarbooz","thannimathan"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 30,
    proteinPer100g: 0.6,
    carbsPer100g: 7.6,
    fatPer100g: 0.2,
    fiberPer100g: 0.4,
    defaultServingDesc: '1 large bowl (250g) = 75 kcal',
    edibleWeightPerUnit: 250,
    category: 'fruits',
    confidence: 'verified',
    healthTip: '92% water content with L-citrulline for cardiovascular recovery.'
  },
  'green apple': {
    canonicalName: 'Fresh Green Granny Smith Apple',
    aliases: ["green apple","granny smith apple","crisp green apple"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 52,
    proteinPer100g: 0.3,
    carbsPer100g: 13.8,
    fatPer100g: 0.2,
    fiberPer100g: 2.4,
    defaultServingDesc: '1 medium apple (150g) = 78 kcal',
    edibleWeightPerUnit: 150,
    category: 'fruits',
    confidence: 'verified',
    healthTip: 'Low glycemic index fruit rich in polyphenols and malic acid.'
  },
  'orange fresh': {
    canonicalName: 'Fresh Whole Orange (Peeled)',
    aliases: ["orange","fresh orange","santra","naranga"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 47,
    proteinPer100g: 0.9,
    carbsPer100g: 11.8,
    fatPer100g: 0.1,
    fiberPer100g: 2.4,
    defaultServingDesc: '1 medium orange (130g edible) = 61 kcal',
    edibleWeightPerUnit: 130,
    category: 'fruits',
    confidence: 'verified',
    healthTip: 'High bioflavonoid Vitamin C source.'
  },
  'broccoli steamed': {
    canonicalName: 'Steamed Broccoli Florets',
    aliases: ["broccoli","steamed broccoli","boiled broccoli","fresh broccoli"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 35,
    proteinPer100g: 2.8,
    carbsPer100g: 7.2,
    fatPer100g: 0.4,
    fiberPer100g: 2.6,
    defaultServingDesc: '1 cup florets (100g) = 35 kcal',
    edibleWeightPerUnit: 100,
    category: 'vegetables',
    confidence: 'verified',
    healthTip: 'Sulforaphane-packed cruciferous vegetable supporting cellular detox.'
  },
  'spinach cheera': {
    canonicalName: 'Steamed Spinach / Cheera Thoran',
    aliases: ["spinach","cheera","palak","boiled spinach","cheera thoran"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 23,
    proteinPer100g: 3,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fiberPer100g: 2.2,
    defaultServingDesc: '1 cup cooked (150g) = 35 kcal',
    edibleWeightPerUnit: 150,
    category: 'vegetables',
    confidence: 'verified',
    healthTip: 'Rich in non-heme iron, magnesium, and lutein.'
  },
  'button mushrooms': {
    canonicalName: 'Sauteed / Grilled White Button Mushrooms',
    aliases: ["mushrooms","button mushrooms","grilled mushrooms","koon"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 28,
    proteinPer100g: 3.1,
    carbsPer100g: 3.3,
    fatPer100g: 0.3,
    fiberPer100g: 1,
    defaultServingDesc: '1 cup (100g) = 28 kcal, 3.1g protein',
    edibleWeightPerUnit: 100,
    category: 'vegetables',
    confidence: 'verified',
    healthTip: 'High umami flavor with almost zero calories. Natural ergosterol Vitamin D precursor.'
  },
  'chicken thigh skinless': {
    canonicalName: 'Cooked Chicken Thigh (Skinless/Boneless)',
    aliases: ["chicken thigh","skinless chicken thigh","grilled chicken thigh"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 177,
    proteinPer100g: 24,
    carbsPer100g: 0,
    fatPer100g: 8.5,
    fiberPer100g: 0,
    defaultServingDesc: '1 medium thigh (100g edible) = 177 kcal, 24g protein',
    edibleWeightPerUnit: 100,
    category: 'proteins',
    confidence: 'verified',
    healthTip: 'Juicy dark meat chicken rich in zinc and B vitamins.'
  },
  'beef roast kerala': {
    canonicalName: 'Kerala Style Dry Beef Roast (Lean Cut)',
    aliases: ["beef roast","kerala beef roast","beef fry","erachi roast","beef olathiyathu"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 210,
    proteinPer100g: 26.5,
    carbsPer100g: 3,
    fatPer100g: 10,
    fiberPer100g: 0.5,
    defaultServingDesc: '100g portion = 210 kcal, 26.5g protein',
    edibleWeightPerUnit: 100,
    category: 'proteins',
    confidence: 'estimated_range',
    healthTip: 'Dense source of bioavailable heme iron, creatine, and carnosine.'
  },
  'green tea unsweetened': {
    canonicalName: 'Pure Green Tea (Unsweetened / 0 kcal)',
    aliases: ["green tea","matcha tea","herbal green tea","black tea unsweetened"],
    basis: '100g',
    weightType: 'edible',
    caloriesPer100g: 1,
    proteinPer100g: 0,
    carbsPer100g: 0.2,
    fatPer100g: 0,
    fiberPer100g: 0,
    defaultServingDesc: '1 cup (200ml) ≈ 2 kcal',
    edibleWeightPerUnit: 200,
    category: 'beverages',
    confidence: 'verified',
    healthTip: 'EGCG catechins that assist metabolic rate and antioxidant defense.'
  },
  'kerala appam': {
    canonicalName: 'Kerala Vellayappam / Palappam (Fermented Rice Pancake)',
    aliases: ["appam","vellayappam","palappam","kerala appam"],
    basis: '100g',
    weightType: 'cooked',
    caloriesPer100g: 135,
    proteinPer100g: 2.1,
    carbsPer100g: 26.5,
    fatPer100g: 2.3,
    fiberPer100g: 0.8,
    defaultServingDesc: '1 medium appam (50g) ≈ 68 kcal',
    edibleWeightPerUnit: 50,
    category: 'grains',
    confidence: 'verified',
    healthTip: 'Fermented yeast/rice pancake with soft spongy center.'
  },
};